image: node:8.12.0

pipelines:
  branches:
    master:
      - step:
          name: Generate Static Files
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts:
            - dist/*
            - dist/**/*
            - dist/**/**